### ISSUE TITLE
Submit offer (milestone)

### ISSUE THREAD

**Issue by xyzerobtc** [zeroauthority-dao/Overview#28]
Instead of a start and end date, only have one or many milestones

**Comment by xyzerobtc** [comment]
0 - upfront payment 
1 - milestone
n - (add) milestone

**Comment by xyzerobtc** [comment]
Use case: 
People who do not want to KYC, let someone else be the lead person

**Comment by xyzerobtc** [comment]
Use case: 
Client wants to add additional administrators.

**Comment by xyzerobtc** [comment]
create a gig, 
select type of gig
![1](https://github.com/zeroauthority-dao/Overview/assets/16929732/e9e90f08-12fd-4dcb-98dc-5a762adacb7c)

**Comment by xyzerobtc** [comment]
add up to 3 milestones 
![2](https://github.com/zeroauthority-dao/Overview/assets/16929732/360cfbd5-4140-4b1b-8dd0-f31d0e473818)

**Comment by xyzerobtc** [comment]
add scope
set target end date for each milestone 
![3](https://github.com/zeroauthority-dao/Overview/assets/16929732/d10a995a-334f-4702-a89a-94e543da1bf2)

**Comment by xyzerobtc** [comment]
select token for payment to lock as collateral 
![4](https://github.com/zeroauthority-dao/Overview/assets/16929732/a4b635c5-b800-41f8-9d6c-65be0048e957)

**Comment by xyzerobtc** [comment]
confirm transaction 
![5](https://github.com/zeroauthority-dao/Overview/assets/16929732/2ae1b97e-bf9e-46b9-acca-d925fdd11b2f)

**Comment by xyzerobtc** [comment]
client will wait for creator to mark a milestone complete
the end date is only for visual 
in the future, we can create logic for the end date to relate to the milestone for clarity contract pending action. 
![Gig mkpl - milestones](https://github.com/zeroauthority-dao/Overview/assets/16929732/d44b52f3-b1bd-4c4f-9b8e-8e8be90936bc)

**Comment by xyzerobtc** [comment]
client will have a new page to mark each milestone complete
contract will release funds when milestone is complete.
![7](https://github.com/zeroauthority-dao/Overview/assets/16929732/3a798b03-573a-44f4-a8f7-c879c6c8478f)

**Comment by SushilBro** [comment]
now we need to change the smart contract right for the milestones.? @xyzerobtc

**Comment by xyzerobtc** [comment]
I think we need a new clarity contract for milestones brother @SushilBro

**Comment by SushilBro** [comment]
Sure brother i will try to add new functions for the milestones🙂

**Comment by HodlSTX** [comment]
I think we will need an end date just for the social side of it. Where it is understood after that date the client will decline all milestones and have their funds returned. We could simply use the information to make the accept button unable to be clicked after that date, just so the client is aware of what was agreed to.

**Comment by xyzerobtc** [comment]
@HodlSTX i like that idea. This makes it so there is actions on both sides to take.

**Comment by HodlSTX** [comment]
We probably don't even need the milestones to be linked to one another per say, the client can create 3 of them, and if the user completes 3, then 1 then 2, our SC should be able to handle that, that should reduce the complexity of this contract.

**Comment by xyzerobtc** [comment]
@HodlSTX if the end date is triggered, the client has 3 days to accept or reject for example??

**Comment by xyzerobtc** [comment]
> We probably don't even need the milestones to be linked to one another per say, the client can create 3 of them, and if the user completes 3, then 1 then 2, our SC should be able to handle that, that should reduce the complexity of this contract.

@HodlSTX would all 3 milestones be under one gig?

**Comment by HodlSTX** [comment]
I'm thinking through this now. 
I am a creator, a client offers me a milestone gig contract for 3 milestones with a due date of 1 month from now, the funds for mile1 mile2 and mile3 are already locked just like in our gig contract. I as the creator have until the end of the month to provide the work to the client. The client at any time can select confirmation of any milestone, this releases the funds to the creator. The creator can have a simple dashboard with the due date and the status of his milestones.

**Comment by HodlSTX** [comment]
After the dead line the client cannot accept the milestones he can only decline, getting his funds back. 
We may want the creator to do one on chain tx at least, so we have some evidence they completed the milestones they said they did. At that point Degrants can use that information in any dispute they have with the creators.

**Comment by HodlSTX** [comment]
A beta release for this milestone based contract could be useful, where the degrants wallet is only allowed to be a client, we could expand it in the future, but that way we don't need as much decentralization and dispute resolution.

**Comment by xyzerobtc** [comment]
> A beta release for this milestone based contract could be useful, where the degrants wallet is only allowed to be a client, we could expand it in the future, but that way we don't need as much decentralization and dispute resolution.

@HodlSTX it would be nice to do a beta release only for DeGrants right now but other people are asking for this to be implemented. I think we need to ship it now and work on implementing a dispute resolution which is easier once we get some samples running through. Eventually we will upgrade contracts to take 5% of total collateral and reward dispute resolvers.

**Comment by HodlSTX** [comment]
The thing I worry about is someone working a milestone contract and they hand over the work and don't get paid, there is really no retribution for that creator.
I think a tx for the creator, confirming they have completed all work for all milestones would be useful. 
If they say yes, client says no, funds get kicked to dao wallet and we do ad hoc dispute resolution.
This would only happen in the case of a rogue client. 
The client has a much more simple process. He sends funds whenever he likes, and can't send funds after the deadline, can only decline. 
All the creator has to do is communicate off chain with client and once all milestones are complete before the deadline, just send that one tx.

**Comment by HodlSTX** [comment]
If the client already sent all the funds, the creator doesn't have to do anything on chain

**Comment by xyzerobtc** [comment]
> The thing I worry about is someone working a milestone contract and they hand over the work and don't get paid, there is really no retribution for that creator. I think a tx for the creator, confirming they have completed all work for all milestones would be useful. If they say yes, client says no, funds get kicked to dao wallet and we do ad hoc dispute resolution. This would only happen in the case of a rogue client. The client has a much more simple process. He sends funds whenever he likes, and can't send funds after the deadline, can only decline. All the creator has to do is communicate off chain with client and once all milestones are complete before the deadline, just send that one tx.

@HodlSTX that’s a really good point. Let’s do it like that. Creator can confirm milestone is complete. And if client says work not completed, goes to DAO review like fixed contract. 
@SushilBro let’s do it this way.
I will add mockups tomorrow.

**Comment by xyzerobtc** [comment]
@SushilBro how long do you think it would take to push update? Hero Gamer wants us to do it February 1st

**Comment by SushilBro** [comment]
@xyzerobtc Brother if i understand what to make then this will not take much time. So please write all the requirements in different points and please be more specific.

**Comment by xyzerobtc** [comment]
Final scope of work - @HodlSTX has advised to create a wrapper on the current gig contract so we can deploy sooner. @SushilBro let me know if you have questions or if you want to jump on a call. 

Milestone Contract Wrapper

- [ ] When you as a client select a creator, a toggle will be up in the top left to switch from gig to milestone, when we flip to milestone, we take the field in each we add the scope and price, and we add 5 of those with the ability to delete each one of them. 
- [ ] Once that is set it goes to page 2 like normal, you add the stx and we have one global field for the end date of the whole thing ( behind the scenes we add this to each gig). 
- [ ] Once sent in our offers and pending work modules we will have a toggle to show milestones (we will also add on our backend a field for the gig to be true false for milestone and the gigs that are associated to it that will be another field)
- [ ] Milestones which are essentially bundled gigs, only thing on the clarity side we would need to do is to have a wrapper function which would carry out the sc functionality we already have like accepting gig1 +2 + 3 . 
- [ ] I think a tx for the creator, confirming each milestone is completed. 
- [ ] If creator say yes, client says no, funds get kicked to DAO wallet and we do ad hoc dispute resolution.
- [ ] The pending work/offers modules will show the milestone data in a different tab, it will show up similar to each gig but they will be packaged together.
- [ ] The client and creator can then work like they have been and if the client wants to send funds they can essentially close out that gig immediately upon acceptance
- [ ] When the client/creator go into the milestone based view they should be able to view all their pending actions, and take action on one or all of them

**Comment by xyzerobtc** [comment]
Add a function on the gig page. If accepted, button on gig page, send 1 pre-payment.

**Comment by xyzerobtc** [comment]
> creator will wait for client to mark a milestone complete [example gig-4] the end date is only informational at this point. in the future, we can create logic for the end date to relate to the milestone for clarity contract pending action. ![Gig mkpl - milestones (1)](https://private-user-images.githubusercontent.com/16929732/297558021-b6f8cb9b-f760-4107-a78b-e70008bcffbc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1Mzc0NjEsIm5iZiI6MTcwNTUzNzE2MSwicGF0aCI6Ii8xNjkyOTczMi8yOTc1NTgwMjEtYjZmOGNiOWItZjc2MC00MTA3LWE3OGItZTcwMDA4YmNmZmJjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDAwMTkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1NDdkZDQyZDA5YWZiZTQzNGE0MGIzZTg5NmViMTE5MTBhMTJmNjMxYTVmMzZmZDUyODY5Mjc4ODE4Mzk1MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MvWI6tkvuOSm0_d1yWE_omwir8Siv7zRcVnKiXoDAI8)

@HodlSTX add detail how this will look similar to individual gig but for milestones.

**Comment by SushilBro** [comment]
How many milestones there can be @xyzerobtc .?

**Comment by xyzerobtc** [comment]
> How many milestones there can be @xyzerobtc .?

@SushilBro no more than 4.

**Comment by SushilBro** [comment]
what should i name them in SC.? @xyzerobtc

**Comment by SushilBro** [comment]
how much commission do we take for each milestone.?. Are milestones all attached in one gig or every milestone has their unique gig-id.?
I want to know if the client selected milestones-based payment then the gig-id will start from 1 right.? We don't need any information from the fixed contract. And we are not connecting this milestone contract with the fixed contract right.?

**Comment by xyzerobtc** [comment]
@HodlSTX I think it should be 2.5% on the total amount not on each milestone. So it won’t matter if we have 1 or 5 milestones.

**Comment by xyzerobtc** [comment]
@SushilBro thank you for the work on this. @HodlSTX and I were talking and we will launch first version of milestone SC as a closed beta. We will whitelist wallets who want to participate.

**Comment by SushilBro** [comment]
@xyzerobtc , @HodlSTX Guys i have created SC where now the client can create a milestone gig, creator can accept it, decline it, and if the work is accepted then the client can unlock other milestone and send the remaining amount to the creator. If it is not accepted and if the time expired then client can redeem back the amount. In addition, if it is accepted and if other milestones are not done by the creator then he can redeem back the remaining fund after the expiry date. What functions should i add now.?

**Comment by xyzerobtc** [comment]
@SushilBro can the client add up to 5 milestones?
Is the start date the date the offer is submitted?
Is the final end date, the date entered by the client? 
@HodlSTX what else do we need? 
there will be no dispute so this sound like enough.

**Comment by SushilBro** [comment]
@xyzerobtc the client should enter the milestones while creating a gig, they cannot add once the gig is created.

**Comment by SushilBro** [comment]
> @SushilBro can the client add up to 5 milestones? Is the start date the date the offer is submitted? Is the final end date, the date entered by the client? @HodlSTX what else do we need? there will be no dispute so this sound like enough.

Yes,  the start date is the block-height when the clients creates the gig and end date is the number of blocks in which artist has to end the work after accepting it.

**Comment by xyzerobtc** [comment]
> @xyzerobtc the client should enter the milestones while creating a gig, they cannot add once the gig is created.

@SushilBro makes sense brother thanks

**Comment by xyzerobtc** [comment]
Off-chain DB changes. 
Which gig-id's are related to the milestone. 
Need to link milestone table to the profile table (who is the client and who is the creator)

**Comment by xyzerobtc** [comment]
![9Gig mkpl - milestones (5)](https://github.com/zeroauthority-dao/Overview/assets/16929732/3f439eab-cd58-4cf1-bff9-965e17b20b49)

**Comment by xyzerobtc** [comment]
![10Gig mkpl - milestones (5)](https://github.com/zeroauthority-dao/Overview/assets/16929732/e00286a7-9a1f-4c43-b2c4-9e476a7e0931)

**Comment by xyzerobtc** [comment]
Decide what the new naming convention
Milestone1
MGIG-01
M1/GIG01
MGIGu1

Off-chain Milestone DB
M1 
M2

Off-chain Milestone DB
M1-GIG-3
M1-GIG-3
M1-GIG-3
M2-GIG-1
M2-GIG-2
